name: 'GAWG Quality action'
description: 'This action is used to analyze the quality of the code using SonarCloud.'
author: Álvaro García Pizarro
branding:
  icon: 'lock'
  color: 'gray-dark'

inputs:
  config-json:
    type: string
    description: 'JSON string containing workflow config parameters.'
    required: true
  github-token:
    type: string
    description: 'GitHub token for authentication.'
    required: true
  sonar-token:
    type: string
    description: 'SonarCloud token for authentication.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Skip SonarCloud Scan
      if: ${{ fromJson(inputs.config-json).SONAR == 'disabled' }}
      shell: bash
      run: |
        echo "SonarCloud Scan is disabled. To enable it, set the SONAR variable to 'enabled' in the workflow_config.yml file."
        echo "SonarCloud Scan is disabled. To enable it, set the SONAR variable to 'enabled' in the workflow_config.yml file." >> $GITHUB_STEP_SUMMARY

    - name: Sonar Analysis configuration INFO
      shell: bash
      run: |
        echo "⚠️ HOW TO CONFIGURE SONAR CLOUD? 👇🏼"
        echo "The following configuration is required to enable SonarCloud analysis:"
        echo "1. Go to https://sonarcloud.io/ and create an account."
        echo "2. Create a new project and generate a token."
        echo "To generate a token, go to your SonarCloud account > Security > Generate token."
        echo "3. Go to your repository settings > Secrets > New repository secret and add the token as 'SONAR_TOKEN'."
        echo "4. Create a sonar-project.properties file in the root of your project with the following content:"
        echo "* sonar.organization"
        echo "* sonar.projectKey"
        echo "* sonar.sources"
        echo "* sonar.sourceEncoding"
        echo "Your sonar organization and projectkey can be found in your SonarCloud account in the project settings."
        echo "Note: make sure to disable automatic analysis in SonarCloud."
        echo "Note: You can customize the analysis by adding more properties to the sonar-project.properties file."
        echo "Further information can be found in: https://docs.sonarsource.com/sonarcloud/?_gl=1*9c6cks*_gcl_au*MjE0MDA2MjkyOS4xNzI1Nzg1MjM4*_ga*NjQxNjQ4MDYuMTcyNTc4NTIzNg..*_ga_9JZ0GZ5TC6*MTcyNTc4NTIzNi4xLjEuMTcyNTc4OTYyMS42MC4wLjA"


    - name: Check sonar-token
      if: ${{ fromJson(inputs.config-json).SONAR == 'enabled' }}
      shell: bash
      run: |
        echo "Checking if SONAR_TOKEN is set..."
        if [ -z "${{ inputs.sonar-token }}" ]; then
          echo "❌ Error: SONAR-TOKEN is not set. To set it, go to your repository settings > Secrets > New repository secret and add it as 'SONAR-TOKEN'."
          echo "❌ Error: SONAR-TOKEN is not set. To set it, go to your repository settings > Secrets > New repository secret and add it as 'SONAR-TOKEN'." >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "✅ SONAR-TOKEN is set."
        fi

    - name: SonarCloud Scan
      if: ${{ fromJson(inputs.config-json).SONAR == 'enabled' }}
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}